language: java

addons:
  sonarcloud:
    organization: "lpiskor"
    token:
      secure: ZNRkSRARf0KHL98jE0Nn-w  # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=LPiskor_GildedOrigin